### ISSUE TITLE
Inbox

### ISSUE THREAD

**Issue by mrkenzi** [sonhoang2503/ecommerce-api-v2#1]
Pls, contact me

**Comment by sonhoang2503** [comment]
Please check your email . I use the email address you put in your github profile.

**Comment by mrkenzi** [comment]
Chào em!
Anh tên Cường, người đã phỏng vấn em ngày hôm qua tại Cty newsky. Hiện tại
a đang có job phù hợp vs em.
E có thể cho a số đt để tiện liên lạc không?

Vào Th 4, 25 thg 5, 2022 lúc 15:18 Jason Nguyen ***@***.***>
đã viết:

**Comment by sonhoang2503** [comment]
E chào a ,
Số điện thoại của em : 0327353390
